apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: futuratickets
  labels:
    app: alertmanager
    tier: monitoring
spec:
  type: ClusterIP
  ports:
    - port: 9093
      targetPort: 9093
      protocol: TCP
      name: http
  selector:
    app: alertmanager
