apiVersion: apps/v1
kind: Deployment
metadata:
  name: marketplace
  namespace: futuratickets
  labels:
    app: marketplace
    tier: frontend
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: marketplace
  template:
    metadata:
      labels:
        app: marketplace
        tier: frontend
        version: v1
    spec:
      containers:
        - name: marketplace
          image: ghcr.io/OWNER/REPO-marketplace:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3002
              name: http
          env:
            - name: NODE_ENV
              value: "production"
            - name: NEXT_PUBLIC_API_URL
              value: "https://api.futuratickets.com"
            - name: NEXT_PUBLIC_STRIPE_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: stripe-public-key
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /
              port: 3002
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 3002
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
      imagePullSecrets:
        - name: ghcr-secret
