apiVersion: v1
kind: Service
metadata:
  name: marketplace
  namespace: futuratickets
  labels:
    app: marketplace
    tier: frontend
spec:
  type: ClusterIP
  ports:
    - port: 3002
      targetPort: 3002
      protocol: TCP
      name: http
  selector:
    app: marketplace
