apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: futuratickets
type: Opaque
stringData:
  # IMPORTANT: Replace with a strong password
  # Use: kubectl create secret generic redis-secret --from-literal=password=YOUR_PASSWORD
  password: CHANGE_ME_IN_PRODUCTION
