apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin
  namespace: futuratickets
  labels:
    app: admin
    tier: frontend
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
        tier: frontend
        version: v1
    spec:
      containers:
        - name: admin
          image: ghcr.io/OWNER/REPO-admin:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3001
              name: http
          env:
            - name: NODE_ENV
              value: "production"
            - name: NEXT_PUBLIC_FUTURA
              value: "https://api.futuratickets.com"
            - name: NEXT_PUBLIC_ACCESS
              value: "wss://access.futuratickets.com"
            - name: NEXT_PUBLIC_MARKETPLACE
              value: "wss://marketplace.futuratickets.com"
            - name: NEXT_PUBLIC_GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: admin-secret
                  key: google-client-id
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /
              port: 3001
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 3001
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
      imagePullSecrets:
        - name: ghcr-secret
