apiVersion: v1
kind: Service
metadata:
  name: admin
  namespace: futuratickets
  labels:
    app: admin
    tier: frontend
spec:
  type: ClusterIP
  ports:
    - port: 3001
      targetPort: 3001
      protocol: TCP
      name: http
  selector:
    app: admin
