apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: futuratickets
  labels:
    app: api
    tier: backend
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
        tier: backend
        version: v1
    spec:
      containers:
        - name: api
          image: ghcr.io/OWNER/REPO-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              name: http
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "3000"
            - name: MONGO_URL
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: mongo-url
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: password
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: jwt-secret
            - name: JWT_EXPIRES_IN
              value: "7d"
            - name: STRIPE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: stripe-secret-key
            - name: STRIPE_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: stripe-public-key
            - name: STRIPE_WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: stripe-webhook-secret
            - name: AZURE_STORAGE_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: azure-storage-connection
            - name: AZURE_STORAGE_CONTAINER_NAME
              value: "futuratickets"
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: sentry-dsn
                  optional: true
            - name: SENTRY_RELEASE
              value: "futura-tickets-api@1.0.0"
            - name: CORS_ORIGINS
              value: "https://admin.futuratickets.com,https://futuratickets.com"
            - name: ENABLE_SWAGGER
              value: "false"
            - name: THROTTLE_TTL
              value: "60000"
            - name: THROTTLE_LIMIT
              value: "100"
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
      imagePullSecrets:
        - name: ghcr-secret
