apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: futuratickets
  labels:
    app: api
    tier: backend
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: api
