apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: futuratickets
  labels:
    app: mongodb
    tier: database
spec:
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
      name: mongo
  selector:
    app: mongodb
