apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: futuratickets
  labels:
    app: grafana
    tier: monitoring
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: grafana
