name: Development CI

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

env:
  NODE_VERSION: '22.17.0'

jobs:
  lint-admin-api:
    name: Lint Admin API
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: futura-tickets-admin-api

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: futura-tickets-admin-api/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint || echo "Linting completed with warnings"

  lint-admin-frontend:
    name: Lint Admin Frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: futura-tickets-admin

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: futura-tickets-admin/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint || echo "Linting completed with warnings"

  lint-marketplace:
    name: Lint Marketplace
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: futura-market-place-v2

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: futura-market-place-v2/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint || echo "Linting completed with warnings"

  build-check:
    name: Build Check
    runs-on: ubuntu-latest
    needs: [lint-admin-api, lint-admin-frontend, lint-marketplace]

    strategy:
      matrix:
        project: [futura-tickets-admin-api, futura-tickets-admin, futura-market-place-v2]

    defaults:
      run:
        working-directory: ${{ matrix.project }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: ${{ matrix.project }}/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

  summary:
    name: CI Summary
    runs-on: ubuntu-latest
    needs: [build-check]
    if: always()

    steps:
      - name: Check status
        run: |
          if [ "${{ needs.build-check.result }}" == "success" ]; then
            echo "✅ All checks passed!"
            exit 0
          else
            echo "❌ Some checks failed"
            exit 1
          fi
