name: Staging CI/CD

on:
  push:
    branches: [staging]
  pull_request:
    branches: [staging]

env:
  NODE_VERSION: '22.17.0'

jobs:
  lint-and-build:
    name: Lint & Build All Projects
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project:
          - name: admin-api
            path: futura-tickets-admin-api
          - name: admin-frontend
            path: futura-tickets-admin
          - name: marketplace
            path: futura-market-place-v2

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: ${{ matrix.project.path }}/package-lock.json

      - name: Install dependencies
        working-directory: ${{ matrix.project.path }}
        run: npm ci

      - name: Run ESLint
        working-directory: ${{ matrix.project.path }}
        run: npm run lint || echo "⚠️ Linting completed with warnings"

      - name: Build project
        working-directory: ${{ matrix.project.path }}
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.project.name }}-build
          path: |
            ${{ matrix.project.path }}/dist
            ${{ matrix.project.path }}/.next
          retention-days: 7

  notify:
    name: Notify Team
    runs-on: ubuntu-latest
    needs: lint-and-build
    if: always() && github.event_name == 'push'

    steps:
      - name: Build status
        run: |
          if [ "${{ needs.lint-and-build.result }}" == "success" ]; then
            echo "✅ Staging build successful!"
          else
            echo "❌ Staging build failed!"
            exit 1
          fi
