name: CI Pipeline
on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]
jobs:
  test-backends:
    name: Backend APIs Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - futura-tickets-admin-api
          - futura-market-place-api
          - futura-access-api
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install and Build
        working-directory: ./service
        run: |
          npm ci --legacy-peer-deps
          npm run build
  security:
    name: Security Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check for secrets
        run: |
          if git grep -E "(sk_live_|pk_live_|mongodb\+srv.*:)"; then
            echo "ERROR: Secrets detected!"
            exit 1
          fi
          echo "No secrets detected"
      - name: Check for .env files
        run: |
          if git ls-files | grep "\.env$"; then
            echo "ERROR: .env files committed!"
            exit 1
          fi
          echo "No .env files in repo"
